# permissions for end users to edit mycrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-crd
    app.kubernetes.io/managed-by: kustomize
  name: app-mycrd-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - mycrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - mycrds/status
  verbs:
  - get
